### ISSUE TITLE
Cannot call method 'baseUrl' of undefined

### ISSUE THREAD

**Issue by komrad** [patrickml/braintree#5]
Hi Patrick,

Just added your package trying to get some API calls going. However, when doing the BrainTreeConnect  = BrainTreeConnect(key) call from your example I get an error:

```
TypeError: Cannot call method 'baseUrl' of undefined
    at Config.baseUrl (/Users/Ricardo/.meteor/packages/patrickml_braintree/.1.0.2.g562y++os+web.browser+web.cordova/npm/node_modules/braintree/lib/braintree/config.js:36:29)
    at Config.baseMerchantUrl (/Users/Ricardo/.meteor/packages/patrickml_braintree/.1.0.2.g562y++os+web.browser+web.cordova/npm/node_modules/braintree/lib/braintree/config.js:40:17)
    at new TransparentRedirectGateway (/Users/Ricardo/.meteor/packages/patrickml_braintree/.1.0.2.g562y++os+web.browser+web.cordova/npm/node_modules/braintree/lib/braintree/transparent_redirect_gateway.js:39:34)
    at new BraintreeGateway (/Users/Ricardo/.meteor/packages/patrickml_braintree/.1.0.2.g562y++os+web.browser+web.cordova/npm/node_modules/braintree/lib/braintree/braintree_gateway.js:66:32)
    at new connect (/Users/Ricardo/.meteor/packages/patrickml_braintree/.1.0.2.g562y++os+web.browser+web.cordova/npm/node_modules/braintree/lib/braintree.js:40:10)
    at BrainTreeConnect (packages/patrickml:braintree/braintree.js:16:1)
    at repl:1:21
    at /Users/Ricardo/Desktop/Meteor/relogo/.meteor/local/build/programs/server/shell-server.js:243:23
```

I run the app from localhost. 

Any idea what causes this?

**Comment by patrickml** [comment]
Hmm i haven't seen this one b4. Can you give me an example of the code you are trying to run?

**Comment by patrickml** [comment]
Here is an example of how I execute my code 

```

var bt = BrainTreeConnect({
        environment: Braintree.Environment.Sandbox,
        merchantId: Meteor.settings.BRAIN_TREE.MERCHANT_ID,
        publicKey: Meteor.settings.BRAIN_TREE.PUBLIC_KEY,
        privateKey: Meteor.settings.BRAIN_TREE.PRIVATE_KEY
      });

      var charge = bt.transaction.sale({
        amount: String(receipt.total),
        merchantAccountId: supplier.profile.merchantAccount.id,
        customerId: user.profile.billing.customerId,
        options: {
          submitForSettlement: true,
          holdInEscrow: true
        },
        serviceFeeAmount: String(receipt.profit),
        taxAmount: String(receipt.tax)
      });

```

**Comment by komrad** [comment]
Thanks for this. I noticed I tried putting my Sandbox CSE Key into the 'BrainTreeConnect = BrainTreeConnect(key)'  from your Readme example (1st line), while the CSE key is meant for the client-side braintree object creation. Deleting this line allowed me to set up the getClientToken I wanted:

var bt;

Meteor.startup(function () {
    bt = BrainTreeConnect({
        environment: Braintree.Environment.Sandbox,
            merchantId: Meteor.settings.BRAIN_TREE.MERCHANT_ID,
            publicKey:  Meteor.settings.BRAIN_TREE.PUBLIC_KEY,
            privateKey: Meteor.settings.BRAIN_TREE.PRIVATE_KEY
        });
});

Meteor.methods({
    getClientToken: function(){
    var token =  bt.clientToken.generate({});
    console.log(token.clientToken);
    return token.clientToken;
    }
});

**Comment by patrickml** [comment]
Awesome, Im glad you were able to figure it out. If you ever have any questions don't hesitate to ask!
